name: bdk_dart_ffi
description: A modern, lightweight, descriptor-based wallet library bridged by Rust.
version: 1.0.0
repository: https://github.com/AstroxNetwork/bdk_dart
issue_tracker: https://github.com/AstroxNetwork/bdk_dart/issues
publish_to: none

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter_rust_bridge: '>=2.1.0 <2.2.0'
  freezed_annotation: ^2.2.0

dev_dependencies:
  lints: # transparent
  build_runner: ^2.1.11
  ffi: ^2.1.0
  ffigen: ^11.0.0
  freezed: ^2.5.2
