name: bdk_dart_ffi
description: A modern, lightweight, descriptor-based wallet library bridged by Rust.
version: 1.0.0
repository: https://github.com/AstroxNetwork/bdk_dart
issue_tracker: https://github.com/AstroxNetwork/bdk_dart/issues
publish_to: none

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  freezed_annotation: ^3.0.0
  flutter_rust_bridge: ^2.11.1

dev_dependencies:
  lints: # transparent
  build_runner: ^2.1.11
  ffi: ^2.1.0
  ffigen: ^18.0.0
  freezed: ^3.0.0
