[package]
name = "bdk_dart"
version = "1.0.0"
authors = ["AstroX Dev <dev@astrox.network>"]
edition = "2018"

[lib]
name = "bdk_dart"
crate-type = ["staticlib", "cdylib"]

[dependencies]
anyhow = "=1.0.86"
base64 = "=0.22.1"
bip32 = "=0.4.0"
bip39 = "=2.0.0"
flutter_rust_bridge = "=2.5.0"
hex = "=0.4.3"
lazy_static = "=1.5.0"
sha2 = "=0.10.8"

[dependencies.bitcoin]
default-features = false
features = ["serde", "base64", "rand"]
version = "=0.29.2"

[dependencies.bdk_lite]
path = "../bdk_lite"
version = "=0.28.0"
features = ["all-keys", "use-esplora-ureq", "sqlite-bundled", "rpc", "electrum"]

[dependencies.k256]
version = "=0.11.6"
default-features = false
features = ["ecdsa", "sha256", "pem", "keccak256", "ecdh", "schnorr"]

[dependencies.miniscript]
version = "=9.0.2"
features = ["serde"]
default-features = false

[dependencies.serde]
version = "=1.0.204"
features = ["derive"]

[dependencies.serde_json]
version = "=1.0.120"

[dependencies.tokio]
version = "=1.38.1"
default-features = false
features = ["rt-multi-thread", "time", "sync"]

[dev-dependencies]
assert_matches = "1.5.0"

[build-dependencies]
flutter_rust_bridge_codegen = "=2.4.0"

[profile.release]
debug = false
opt-level = "z"
lto = true
